### ISSUE TITLE
Swarm for more then one torrent

### ISSUE THREAD

**Issue by FLYBYME** [feross/bittorrent-swarm#11]
Can you use a single swarm for more then one torrent?

**Comment by FLYBYME** [comment]
Stupid question. Did more reading and found my question was parsed wrong.


My question is more.. why not use one server for more then one torrent.

**Comment by feross** [comment]
You create a new `Swarm` instances for each torrent. If you call `swarm.listen` with same port number, the same server is automatically re-used. :+1:

**Comment by feross** [comment]
Going to close this issue, but feel free to open a new issue for additional questions :)
