### ISSUE TITLE
TypeError: Object #<Object> has no method 'forEach'

### ISSUE THREAD

**Issue by FLYBYME** [feross/bittorrent-swarm#12]
Getting this error dont know where its coming from.
```
/home/bob/code/torrent-swarm/node_modules/bittorrent-swarm/index.js:186
    this.swarms.forEach(function (swarm) {
                ^
TypeError: Object #<Object> has no method 'forEach'
    at Pool._onerror (/home/bob/code/torrent-swarm/node_modules/bittorrent-swarm/index.js:186:17)
    at Server.emit (events.js:95:17)
    at TCP.onconnection (net.js:1171:10)
```

**Comment by feross** [comment]
It appears that the tcp server is emitting an error, but there's a bug in this module that prevented the real error message from getting emitted. Update `bittorrent-swarm` to 1.1.2 and try again. You should get an 'error' event on the swarm object with more details.

```js
swarm.on('error', function (err) {
  console.error(err.stack)
})
```

My guess is that the port you're trying to use is already in use.
