### ISSUE TITLE
Limit to one interface

### ISSUE THREAD

**Issue by corelgott** [feross/bittorrent-swarm#13]
Hi,

it's more or less a feature request… I'd like to limit the torrent traffic to a single interface.

To achieve this, I changed `Line 483` to

    var conn = net.connect({ localAddress: bind, port : parts[1], host : parts[0]});

where bind is the IP of the interface I want to limit the traffic to. The problem is, if the interface goes down and comes up again (I find the new IP) the torrrent is not resuming since the `this.numConns >= this.maxConns` is most likely matched. So what event to fire / how to clean up the connection if it's not able to be opened. This corresponds to the todo in `Line 538`- `retry or end connection?`.

How to cleanly destroy the connection that new connection are being initiated?

**Comment by feross** [comment]
There are really two issues here:

- allow listening on just a single interface
- handle errored connections better

**Comment by corelgott** [comment]
You are definitely right – the first one: Listening on only one interface i've already solved via the localAddress option. Here is the full code, how I tackled the problem: (Even though this is extremely inefficient)

    // define the interface to limit to
    var bindInterface = 'utun0';
    var bind = '0.0.0.0';
    // if there is a device to limit to
    if (bindInterface !== undefined) {
        var eths = os.networkInterfaces();
        bind = undefined;

        for (var eth in eths)
            if (eth == bindInterface) {
                bind = eths[eth][0].address;
                break;
            }
    }

    if (bind === undefined) return;
    var parts = addrToIPPort(peer.addr)
    var conn = net.connect({ localAddress: bind, port : parts[1], host : parts[0]});

The second one is a more structural problem, which I wasn't able to solve up to now.

**Comment by feross** [comment]
The first issue (allow listening on just a single interface) is fixed in 4.0.1.

Handling errored connections seems to be working better, and the TODO you referenced isn't in the codebase anymore, so I'm going to close this issue :-)
