### ISSUE TITLE
Wire.handshake: Buffer.fill can return undefined, resulting in "Cannot read property 'length'" in the handshake event

### ISSUE THREAD

**Issue by dpkirchner** [feross/bittorrent-swarm#22]
Running `npm install && npm test` on a freshly checked out copy of webtorrent results in this exception:

    # Download using webseed (via magnet uri)
    ok 448 should be equal
    ok 449 should be equivalent
    TypeError: Cannot read property 'length' of undefined
        at WebConn.Wire.handshake (/Users/dpk/Documents/git/webtorrent/node_modules/bittorrent-swarm/node_modules/bittorrent-protocol/index.js:190:39)

The problem appears to be that the `handshake` event listener in `WebConn` tries to pass in the result of `Buffer.fill` as a buffer to `Wire.handshake`. However, `Buffer.fill` can return undefined, at least on node v0.10.36. Best I can tell, `Buffer.fill`'s return value is not documented (https://nodejs.org/api/buffer.html#buffer_buf_fill_value_offset_end, no "return"), meaning the code may be relying on undefined behavior.

This change fixes the problem in `lib/webconn.js`

    -    self.handshake(infoHash, new Buffer(20).fill(url))
    +    var buf = new Buffer(20)
    +    buf.fill(url)
    +    self.handshake(infoHash, buf)

I was going to throw together a proper PR but I'm not yet sure how to even write a test for this (I just don't understand the code well enough to even name the test).

**Comment by bertofer** [comment]
I get the same error when trying to download from the browser.

**Comment by feross** [comment]
Thanks for the bug report. You're right – `buffer.fill()` returns `undefined` on node 0.10. Later node versions return the buffer from `buffer.fill()` for chainability.

We shouldn't be slicing off the url anyway, since that creates the chance for a collision between two web seeds where the first 20 characters of the url are the same. We can fix this by using the SHA1 hash of the web seed url.

**Comment by feross** [comment]
This is fixed in 6.0.0.
