### ISSUE TITLE
once torrent is downloaded it keeps connecting to the same peer indefinitely

### ISSUE THREAD

**Issue by marmolejo** [feross/bittorrent-swarm#6]
Once the torrent is downloaded (0 pieces missing), the swarm keeps on connecting to the same peer again and again. The test torrent only has one seed. So this is the only peer that is in the swarm. 

After analyzing it with wireshark, for some reason, bittorrent-client is still interested, so remote peer sends unchoke. After timeout, remote peer closes connection. bittorrent-swarm doesn't remove the peer and inserts again in the queue. This is the output:

> bittorrent-swarm connect to 112.43.2.43:48534 (numConns 0 numPeers 0) +28s browser.js:119
> bittorrent-protocol new wire +80ms browser.js:119
> bittorrent-client:torrent port message from 112.43.2.43:48534 +912ms browser.js:119
> bittorrent-swarm connect to 112.43.2.43:48534 (numConns 0 numPeers 0) +30s browser.js:119
> bittorrent-protocol new wire +15s browser.js:119
> bittorrent-client:torrent port message from 112.43.2.43:48534 +878ms browser.js:119
> bittorrent-swarm connect to 112.43.2.43:48534 (numConns 0 numPeers 0) +30s browser.js:119
> bittorrent-protocol new wire +77ms browser.js:119
> bittorrent-client:torrent port message from 112.43.2.43:48534 +921ms browser.js:119
> bittorrent-swarm connect to 112.43.2.43:48534 (numConns 0 numPeers 0) +18s browser.js:119
> bittorrent-protocol new wire +77ms browser.js:119
> bittorrent-client:torrent port message from 112.43.2.43:48534 +921ms

**Comment by feross** [comment]
The module was rewritten from scratch for WebRTC support, so this issue is stale.
